language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t ben/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ben/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-924486238100"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

