# language: generic 
# sudo: required
# services:
#   - docker


# before_install:
#   - docker build -t ben/docker-react -f Dockerfile.dev .

# script:
#   - docker run -e CI=true ben/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-1"
#   app: "docker-react"
#   env: "DockerReact-env"
  # bucket_name: "elasticbeanstalk-ap-northeast-1-924486238100"
  # backet_path: "docker-react"
#   on:
#     branch: master
#   access_key_id:
#     secure: "$AWS_ACCESS_KEY"
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"

language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ben/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ben/docker-react npm run test

deploy:
  - provider: s3
    bucket_name: "elasticbeanstalk-ap-northeast-1-924486238100"
    backet_path: "docker-react"
    region: "ap-northeast-1"
    app: "docker-react"
    env: "DockerReact-env"
    on:
      branch: master
    access_key_id:
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
  - provider: travis-ci
    access_key_id:
      secure: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
    bucket_name: "elasticbeanstalk-ap-northeast-1-924486238100"
    backet_path: "docker-react"
    key: "lastest.zip"
    application: travis-ci
    deployment_group: master
    region: ap-northeast-1
    on:
      branch: master


